### ISSUE TITLE
Use of remote_theme

### ISSUE THREAD

**Issue by rgaiacs** [carpentries/styles#229]
@dpshelio asked to prototype using https://blog.github.com/2017-11-29-use-any-theme-with-github-pages/ to "simplify" the building process.

**Comment by dpshelio** [comment]
In my free time -- which is scarce -- I'm looking into that.  I'll add here any updates.

**Comment by rgaiacs** [comment]
@dpshelio Thanks very much.

@fmichonneau Could you add this to be discussed on the 23 May meeting?

**Comment by klieret** [comment]
Hi @dpshelio @rgaiacs @fmichonneau  . I'm curious about this change. Was there any specific reason you decided against this? This seems to be a very elegant solution for sharing common parts of code between the different repositories.

I'm part of an organization (HSF Training) that develops training modules based on your template (thank you! :heart:) for the high energy physics community and we have been recently discussing this exact change ([here](https://github.com/hsf-training/hsf-training-cpp-webpage/issues/18)), because the number of our repositories continues to increase.

We'd be very happy to hear about your 2021 opinion on this :)

**Comment by maxim-belkin** [comment]
@klieret, check out [carpentries/carpentries-theme](https://github.com/carpentries/carpentries-theme) repo

**Comment by klieret** [comment]
Thanks a lot @maxim-belkin Exactly what we were looking for! I'm just curious that both `styles` and `carpentries-theme` currently coexist (and seem to be maintained somewhat separately). Why don't you simply remove all style files form `styles` and instead add `carpentries-theme` to its `Gemfile`?

**Comment by fmichonneau** [comment]
Hi @klieret 

We have both because we have many lessons that use and rely on `styles`, and the remote theme doesn't allow us to have other scripts our infrastructure needs (e.g., scripts run by `make lesson-check`).

All the commits in `styles` that affect the remote theme are synchronized regularly.

As a side-note, we are working on the next iteration of our lesson template which is [designed](https://github.com/carpentries/sandpaper#readme) to better compartmentalize styling, building, and checking. 

Thanks!
