### ISSUE TITLE
differentiate `code` elements that are links

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/styles#254]
Currently:

```
`tidyverse` and [`tidyverse`](http://tidyverse.org/)
```

can't be distinguished when rendered:

![screenshot from 2018-05-17 14-57-07](https://user-images.githubusercontent.com/5502922/40197856-ae8d701e-59e2-11e8-9f06-adec85a1313a.png)

**Comment by rgaiacs** [comment]
@fmichonneau Thanks to bring this up. Taking https://github.com/swcarpentry/lesson-example/pull/201 into consideration, would not be the case that we should **not** be using backtick quotes inside links? We should use code element when tidyverse is part of one R command, e.g. `install.packages("tidyverse")`, but we could drop the code element when talking about it as a package/tool, e.g. "See how the tidyverse makes data science faster". We only need link for the last case.

**Comment by unode** [comment]
https://gist.github.com/unode/44330ffb793cbcdffdf31541a428e74b fixed it for us.

**Comment by maxim-belkin** [comment]
It would be great if you could submit a PR updating the color of `a code` elements only, @unode.

**Comment by unode** [comment]
@maxim-belkin happy to do the PR but both changes are required to have `code` and [`link`]() (using same style as GitHub) due to CSS hierarchy rules.

The default style uses the *hyperlink* color on non-hyperlinks, which was one of the reasons for confusion.
As @fmichonneau shows in the screenshot above, you cannot tell which code blocks have links without hovering. Most readers don't notice and miss the links.

**Comment by maxim-belkin** [comment]
> @maxim-belkin happy to do the PR but both changes are required to have `code` and `link` (using same style as GitHub) due to CSS hierarchy rules.

No, you can add `a code { color: red; }` after `code { ... }` to get 
![image](https://user-images.githubusercontent.com/13123663/88322628-9d310000-cce6-11ea-8f16-bd092c9a5757.png)

**Comment by unode** [comment]
Sure, the point was to not have plain code in blue which is often used for links, as it happens here on GitHub.

**Comment by maxim-belkin** [comment]
If that's the goal then yes. I thought we want to keep the default code blocks "as is" (because this is a pretty significant change) and update "code in links" (hence, `a code`) only.

I'm OK with this change if others like the new color. New contrast is pretty good, so no issues from accessibility standpoint.
