### ISSUE TITLE
Using Github Actions instead of Travis-CI for deployment

### ISSUE THREAD

**Issue by angela-li** [carpentries/styles#456]
With the new rollout of Github Actions, this could be a replacement for custom Travis deployment. Doesn't need to be a big priority, since Travis works on the lessons, but could make it easier to manage repos? 

Worth doing some research into and seeing if this would be helpful.

**Comment by maxim-belkin** [comment]
We can easily move from Travis to GitHub Actions but I'm not sure if it is going to simplify the management aspect because GH Actions is just an engine that runs whatever code we tell it to run. What GitHub Actions allow us to do is run tests on multiple platforms (macOS, Linux, and Windows) and, therefore, see if the changes we make work across the spectrum of operating systems we target.

**Comment by fmichonneau** [comment]
We have migrated to GitHub Actions now.
